
export interface Quote {
  id: number;
  text: string;
}

export enum AppSection {
  ENVELOPE = 'ENVELOPE',
  GREETING = 'GREETING',
  GRATITUDE = 'GRATITUDE',
  EXPANDED_GRATITUDE = 'EXPANDED_GRATITUDE',
  FIRST_MET = 'FIRST_MET',
  PROPOSAL = 'PROPOSAL',
  FESTIVALS = 'FESTIVALS',
  MEMORIES_STRENGTH = 'MEMORIES_STRENGTH',
  MEMORIES_GALLERY = 'MEMORIES_GALLERY',
  CANVAS_GALLERY = 'CANVAS_GALLERY',
  ANNIVERSARIES = 'ANNIVERSARIES',
  CINEMATIC_STORY = 'CINEMATIC_STORY',
  FUTURE_DREAMS = 'FUTURE_DREAMS',
  ROMANTIC_GALLERY = 'ROMANTIC_GALLERY',
  ROMANTIC = 'ROMANTIC',
  PROMISE = 'PROMISE',
  CLOSING = 'CLOSING'
}
